config/routes.rb
SteerClear::Application.routes.draw do

  devise_for :workers, :controllers => { :registrations => "workers/registrations", :sessions => "workers/sessions" }

  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions" }

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  resources :shifts

  root :to => 'pages#home'


  match '/workers/startShift', :to => 'shifts#create'
  match '/workers/inService/', :to => 'shifts#makeInService'
  match '/workers/offService/', :to => 'shifts#makeOffService'
  match '/workers/endShift/', :to => 'shifts#endShift'
  match '/workers/updateAddress', :to => 'shifts#updateAddress'

  match '/createRequest', :to => 'rideRequests#create'
  match '/users/showRequest/:id(.:format)', :to => 'rideRequests#show'
  match '/updateRequest', :to => 'rideRequests#update'
  match '/destroyRequest/', :to => 'rideRequests#destroy'


  match '/users', :to => 'users#show'
  match '/workers', :to => 'workers#show'
  match '/about',   :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/employees', :to => 'pages#employeeinfo'

  #for static hosted files
  match '/ConstitutionBylaws.pdf', :to => 'pages#download_bylaws'
  match '/HiringContract.doc', :to => 'pages#download_contract'
  match '/TrainingEmploymentPacket2012-13.docx', :to => 'pages#download_training'
  match '/PayrollProcess2012.doc', :to => 'pages#download_payroll'

end

app/views/layouts/_footer.html.erb
<small>
  WM Steer Clear
</small>
<nav>
  <ul>
    <li><%= link_to "About Us",   about_path %></li>
    <li><%= link_to "Contact Us", contact_path %></li>
    <li><%= link_to "Employees", employees_path %></li>
    <li><a href="http://wm.edu/">WM</a></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SteerClear" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Steer Clear</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav pull-right">
              <% if user_signed_in? %>
                <!-- links for logged in users -->
                <li><%= link_to "My Rides", "/users"  %></li>
                <li><%= link_to "Edit User Profile", "/users/edit"  %></li>
                <li><%= link_to "Log Out", "/users/sign_out", method: "delete"  %></li>
              <% elsif worker_signed_in? %>
                  <!-- links for logged in workers -->
                  <li><%= link_to "Worker Dashboard", "/workers"  %></li>
                  <li><%= link_to "Edit Profile", "/workers/edit"  %></li>
                  <li><%= link_to "Log Out", destroy_worker_session_path, :data => { :confirm => "Warning: This will end your shift and re-queue any rides you have accepted. Please ensure you have completed your shift." }, method: "delete"  %></li>
              <% else %> <!-- for non-logged on users/workers -->
                  <li><%= link_to "Sign Up", "/users/sign_up" %></li>
                  <li><%= link_to "Log In", "/users/sign_in" %></li>
              <% end %>
              <!-- end links -->
            </ul>
          </div><!-- end .nav-collapse menu -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">  <!-- row for alerts -->
        <!--<div class="span6 offset3"><div class="alert-info"> <%= bootstrap_flash %></div></div> &lt;!&ndash; alerts may need more fixing &ndash;&gt;-->
        <div class="span6 offset3">
          <div class="hidden-phone">
            <% flash.each do |key, value| %>
                <div class="alert alert-<%= key %>">
                  <%= value %>
                  <a class="close" data-dismiss="alert" href="#">&times;</a>
                </div>
            <% end %>
          </div>
        </div>

        <div class="visible-phone phone-flashes">
          <% flash.each do |key, value| %>
              <div class="alert alert-<%= key %>">
                <%= value %>
                <a class="close" data-dismiss="alert" href="#">&times;</a>
              </div>
          <% end %>
        </div>
       <!--</div>  &lt;!&ndash; ends row fluid &ndash;&gt;-->

      <!--<div class="row-fluid"> &lt;!&ndash; content row &ndash;&gt;-->
        <div class="span9"> <!-- renders content of the page -->
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <%= render 'layouts/footer' %>  <!-- placeholder, create footer partial with links to about us and worker login -->
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <%= javascript_include_tag "application" %>

  </body>
</html>